import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< Updated upstream
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
=======
import "./globals.css"
import Header from "@/components/layout/Header/Header"
import Footer from '@/components/layout/Footer'
>>>>>>> Stashed changes

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< Updated upstream
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
=======
    <html lang="vi">
      <body className="min-h-screen flex flex-col justify-between bg-gray-200">
        <Header /> 
        <main className="mb-40">
          {children}
        </main>
       <Footer/>
      </body> 
>>>>>>> Stashed changes
    </html>
  );
}
